"""initial schema: analyses, hops, anomalies

Revision ID: 5e9005123f00
Revises:
Create Date: 2026-09-04 09:31:18.526915
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '5e9005123f00'
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source_format', sa.String(length=8), nullable=False),
    sa.Column('raw_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('status_detail', sa.String(length=1024), nullable=True),
    sa.Column('parse_confidence', sa.Float(), nullable=False),
    sa.Column('from_display_name', sa.String(length=512), nullable=True),
    sa.Column('from_address', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.String(length=998), nullable=True),
    sa.Column('message_date', sa.DateTime(), nullable=True),
    sa.Column('spf_result', sa.String(length=16), nullable=True),
    sa.Column('dkim_result', sa.String(length=16), nullable=True),
    sa.Column('dmarc_result', sa.String(length=16), nullable=True),
    sa.Column('dmarc_policy', sa.String(length=16), nullable=False),
    sa.Column('dkim_signature_expired', sa.Boolean(), nullable=False),
    sa.Column('hop_count', sa.Integer(), nullable=False),
    sa.Column('anomaly_count', sa.Integer(), nullable=False),
    sa.Column('highest_anomaly_severity', sa.String(length=16), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('authentication_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sender_domain_intel_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_created_at'), 'analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_analyses_dkim_result'), 'analyses', ['dkim_result'], unique=False)
    op.create_index(op.f('ix_analyses_dmarc_result'), 'analyses', ['dmarc_result'], unique=False)
    op.create_index(op.f('ix_analyses_from_address'), 'analyses', ['from_address'], unique=False)
    op.create_index(op.f('ix_analyses_highest_anomaly_severity'), 'analyses', ['highest_anomaly_severity'], unique=False)
    op.create_index(op.f('ix_analyses_sha256'), 'analyses', ['sha256'], unique=False)
    op.create_index(op.f('ix_analyses_spf_result'), 'analyses', ['spf_result'], unique=False)
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('hop_sequences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.String(length=1024), nullable=False),
    sa.Column('evidence', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_analysis_id'), 'anomalies', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_anomalies_severity'), 'anomalies', ['severity'], unique=False)
    op.create_index(op.f('ix_anomalies_type'), 'anomalies', ['type'], unique=False)
    op.create_table('hops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('raw_header', sa.String(), nullable=False),
    sa.Column('from_host', sa.String(length=512), nullable=True),
    sa.Column('from_ip', sa.String(length=64), nullable=True),
    sa.Column('by_host', sa.String(length=512), nullable=True),
    sa.Column('protocol', sa.String(length=64), nullable=True),
    sa.Column('timestamp_raw', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('parse_confidence', sa.Float(), nullable=False),
    sa.Column('asn', sa.Integer(), nullable=True),
    sa.Column('asn_org', sa.String(length=256), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('enrichment_source', sa.String(length=24), nullable=False),
    sa.Column('is_bogon', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hops_analysis_id'), 'hops', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_hops_from_ip'), 'hops', ['from_ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hops_from_ip'), table_name='hops')
    op.drop_index(op.f('ix_hops_analysis_id'), table_name='hops')
    op.drop_table('hops')
    op.drop_index(op.f('ix_anomalies_type'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_severity'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_analysis_id'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_analyses_status'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_spf_result'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_sha256'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_highest_anomaly_severity'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_from_address'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_dmarc_result'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_dkim_result'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_created_at'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
