"""add ai_signals_json and phishing_probability columns

Revision ID: 8bb8e3bc14fb
Revises: e6db82b15a7e
Create Date: 2026-09-04 18:00:26.391136
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '8bb8e3bc14fb'
down_revision: str | None = 'e6db82b15a7e'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('phishing_probability', sa.Float(), nullable=True))
    op.add_column('analyses', sa.Column('ai_signals_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_analyses_phishing_probability'), 'analyses', ['phishing_probability'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_phishing_probability'), table_name='analyses')
    op.drop_column('analyses', 'ai_signals_json')
    op.drop_column('analyses', 'phishing_probability')
    # ### end Alembic commands ###
