"""add analyst_notes column

Revision ID: c6bb46cc2189
Revises: 8bb8e3bc14fb
Create Date: 2026-09-04 18:58:36.160440
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'c6bb46cc2189'
down_revision: str | None = '8bb8e3bc14fb'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('analyst_notes', sa.String(length=4096), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'analyst_notes')
    # ### end Alembic commands ###
