"""add risk_score and verdict columns

Revision ID: e6db82b15a7e
Revises: 5e9005123f00
Create Date: 2026-09-04 16:52:01.910107
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e6db82b15a7e'
down_revision: str | None = '5e9005123f00'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted by hand ###
    # server_default is required here (even though the ORM-level default is
    # Python-side) so this NOT NULL column can apply against a table that
    # may already have rows -- existing rows get scored 0/"clean" until
    # re-analyzed, which is honest: we have no basis to claim otherwise for
    # data that predates this column.
    op.add_column(
        'analyses', sa.Column('risk_score', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column(
        'analyses', sa.Column('verdict', sa.String(length=16), nullable=False, server_default='clean')
    )
    op.create_index(op.f('ix_analyses_risk_score'), 'analyses', ['risk_score'], unique=False)
    op.create_index(op.f('ix_analyses_verdict'), 'analyses', ['verdict'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_verdict'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_risk_score'), table_name='analyses')
    op.drop_column('analyses', 'verdict')
    op.drop_column('analyses', 'risk_score')
    # ### end Alembic commands ###
