"""make timestamp columns timezone-aware

Revision ID: ee3920f23b74
Revises: c6bb46cc2189
Create Date: 2026-09-04 19:32:02.205246
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ee3920f23b74'
down_revision: str | None = 'c6bb46cc2189'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # Existing values are naive TIMESTAMP columns that were always
    # populated from Postgres's UTC session clock (func.now()) or from
    # datetimes that Postgres itself converted to UTC wall-clock on
    # insert -- so "AT TIME ZONE 'UTC'" is the correct reinterpretation,
    # not a guess. Without it, plain ALTER COLUMN ... TYPE timestamptz
    # would instead assume the naive values are already in the session's
    # local time (also UTC here, so this happens to be a no-op in this
    # environment, but the explicit USING clause makes the migration
    # correct regardless of the server's configured timezone).
    op.alter_column('analyses', 'message_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="message_date AT TIME ZONE 'UTC'")
    op.alter_column('analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using="created_at AT TIME ZONE 'UTC'")
    op.alter_column('hops', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="timestamp AT TIME ZONE 'UTC'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hops', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="timestamp AT TIME ZONE 'UTC'")
    op.alter_column('analyses', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               postgresql_using="created_at AT TIME ZONE 'UTC'")
    op.alter_column('analyses', 'message_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               postgresql_using="message_date AT TIME ZONE 'UTC'")
    # ### end Alembic commands ###
